# This is a basic workflow to help you get started with Actions

name: Setup sonarqube

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: warchant/setup-sonar-scanner@v1

    # Runs a single command using the runners shell
    - name: Run sonarqube
      run: sonar-scanner.bat -D"sonar.projectKey=service-lab" -D"sonar.sources=." -D"sonar.host.url=http://localhost:9000" -D"sonar.login=d49038fc781d820856ff0fc245694f81869e635d"

    
